### ISSUE TITLE
Failed to meta load video idx XXXX from PATH when running 'bash exp/uniformer_s8x8_k400/run.sh' from the Uniformer/video_classification directory

### ISSUE THREAD

**Issue by SWE-Ahmed** [Sense-X/UniFormer#103]
Thank you for sharing this repository of the code implementation of the Uniformer paper. However, when I tried to run the implementation using a subset of the data (Kinetics400) I keep getting this error where the video isn't being loaded successfully.
Is there a solution to it?

**Comment by Andy1621** [comment]
Thanks for your question. If your process runs normally (the `stdout.log` outputs the training log), you can ignore the `warning`.

As for the reason, it is mainly because some videos can not be recorded.
https://github.com/Sense-X/UniFormer/blob/849cd0cd3b163f84102b1a799019a689d8d3fb8a/video_classification/slowfast/datasets/kinetics.py#L208-L221
You can check the error video path, and try to record it via `container.get_video_container()` function.
https://github.com/Sense-X/UniFormer/blob/849cd0cd3b163f84102b1a799019a689d8d3fb8a/video_classification/slowfast/datasets/video_container.py#L33-L36
