### ISSUE TITLE
About attention visualization

### ISSUE THREAD

**Issue by ofishhaha** [Sense-X/UniFormer#28]
Thank u for ur efforts!
The pictures in ur paper are beautiful. I wonder did u use **attention rollout** to do the visualization as other transformer models? I tried to visualize it by just calculate the mean of the feature. And the result is not as expected.
I would appreciate it to hear ur recommendation.

**Comment by Andy1621** [comment]
Thanks for your questions. 
For the features in shallow layers, calculating the mean of the features is reasonable to check the difference among different operations, since they learn local features like texture and edges. 
However, in deep layers, only the abstract information is shown in the mean features. I recommend visualizing attention matrix `A` for self-attention, because they mean the importance among tokens. You can refer to [Visualizer](https://github.com/luo3300612/Visualizer).

For attention rollout, You can refer to [here](https://jacobgil.github.io/deeplearning/vision-transformer-explainability) for some help. Maybe you need to modify the codes like [here](https://github.com/hila-chefer/Transformer-Explainability).
In my experiments, those methods like CAM are hard to work for self-attention. Since they are designed for CNNs, there seems to only work for CNNs.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
