### ISSUE TITLE
LLGG --》GGLL?

### ISSUE THREAD

**Issue by xuyu666** [Sense-X/UniFormer#29]
Hello author, I would like to ask a question:
Is the **GGLL** method a feasible solution without considering the memory consumption? Have you tried this combination?

Thanks lol...!

**Comment by Andy1621** [comment]
Thanks for your good question! I have not tried GGLL in my experiments, since it requires large computation. But I have tried to use L+G in all the layers, which means half of the channels are used for L and the rest for G. It achieves slightly lower performance (not bad).

Actually, GGLL has been done in [Stand-Alone Self-Attention in Vision Models](https://arxiv.org/abs/1906.05909). It works not bad with large computations.
<img width="388" alt="image" src="https://user-images.githubusercontent.com/24236723/159681590-093dc6eb-50f0-48e1-baf3-515164931cc9.png">
It work

**Comment by xuyu666** [comment]
Thank you for your patient answer, it is very **useful**, my doubt is solved,！
And I try to integrate this idea into my model.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
