### ISSUE TITLE
Container3D和UniFormer有什么区别吗？

### ISSUE THREAD

**Issue by LeiYiNuist** [Sense-X/UniFormer#37]
你好，我在你的日志里面发现使用的模型叫Container3D_SA_FP32(base的16*4，16*8等使用的都是Container3D_SA_FP32)，也就是说你的结果都是使用的这个模型。但你提供的所有pytorch模型都是UniFormer，那么Container3D_SA_FP32和UniFormer是一样的吗？我很困惑，因为我使用UniFormer base 16*4测试得到的top1只有0.03

**Comment by Andy1621** [comment]
They are the same models actually, I change the model name when writing paper.

For the low accuracy, you may need to check the label file. The label file I used can be found [here](https://github.com/Sense-X/UniFormer/tree/main/video_classification/data_list). Your category index may be different from what I used [here](https://github.com/Sense-X/UniFormer/blob/main/video_classification/data_list/k400/kinetics_400_categroies.txt).

I have met a similar problem when testing the official MViT model because of the different category indexes. You can check it and map the category index.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
