### ISSUE TITLE
threequestions about video classification

### ISSUE THREAD

**Issue by JieHarry-Hu** [Sense-X/UniFormer#45]
Hello,
    I have three operational questions about video classification in uniformer:
    1、I find you write ''resize the video to the short edge size of 320'' in DATASET.md of video_classification, so I wonder whether this operation will be achieved before the program runs. If so, could you offer me the code of 'resize'?
    2、I see you write ''freeze BN in Backbone'' in README.md, are you also forget to perform this operation in video classification? And if it's necessary to perform this operation in video classification?
    3、The Kinetics 400 dataset I downloaded has timestamps between the file name and '.mp4', does it affect the code running?
Thanks for your instruction if you answer my questions.

**Comment by Andy1621** [comment]
1. The videos are resized before the program runs. You can follow the scripts in [MMAction2](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/kinetics) to prepare the data. Since the videos were processed by others, I don't have the processing code. I can provide you with the processed videos if necessary. If you want it, please leave your email~~

2. `Freeze BN` only works when the batch size is too small, which is a popular operation in Object Detection and Semantic Segmentation. I have not used it for video classification. Actually, in previous works like TSN, they freeze BN for UCF101 and HMDB51. In my opinion, the operation only works when fine-tuning special models on a small dataset.

3. In my repo, I read videos for Kinetics via [decord](https://github.com/dmlc/decord), which processes the raw videos. If you also process raw videos, I think it is okay, and you only need to prepare the correct data list as in my [data](https://github.com/Sense-X/UniFormer/tree/main/video_classification/data_list/k400).

**Comment by JieHarry-Hu** [comment]
Thank you so much for your detailed answer, it couldn't be better if you could provide the processed video, my email is h1035196477@hotmail.com. Finally, thank you for your help.

**Comment by Andy1621** [comment]
I have sent it to you email, please check it~~

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.

**Comment by Auroralyxa** [comment]
> I have sent it to you email, please check it~~

Could you please provide me with the processed video, my email is 2273740426@qq.com, thank you in advance
