### ISSUE TITLE
How to compute the FLOPs? 

### ISSUE THREAD

**Issue by DoranLyong** [Sense-X/UniFormer#50]
Thanks to share your nice products :). 
I think your code is arranged well for me to understand. 

I have one question how to compute the FLOPs number like in [your paper](https://arxiv.org/pdf/2201.04676v3.pdf).

do you have a package to compute it? 
or I want to know if you can recommend some tools for it.  

Thanks.

**Comment by Andy1621** [comment]
Thanks for your great questions!

For the image backbone, please check the [README](https://github.com/Sense-X/UniFormer/tree/main/image_classification). I have added some code to use `fvcore` to automatically calculate the accurate FLOPs.

https://github.com/Sense-X/UniFormer/blob/da9b6adffb09923d6be7b4fa718dca6387fe38ff/image_classification/main.py#L258-L259

For the video backbone, you can also use `fvcore`. BTW, the `PySlowfast` repo I used will automatically calculate the FLOPs.

For the downstream tasks, since MMDetection/MMSegmentation/MMPose do not calculate the FLOPs of matrix multiplication, I calculate the FLOPs of extra matrix multiplication manually.

**Comment by DoranLyong** [comment]
Check!  Thanks~  :)
