### ISSUE TITLE
any difference between lucidrains's implemantation?

### ISSUE THREAD

**Issue by he-y** [Sense-X/UniFormer#51]
Hi, may I ask any difference between lucidrains's implementation and this repo?
https://github.com/lucidrains/uniformer-pytorch 
Thanks a lot!

**Comment by Andy1621** [comment]
Thanks for your question! I have not seriously checked the code.
Since the code for video may not be easy separated, if you want to use code for video, maybe you can find it [here](https://huggingface.co/spaces/Sense-X/uniformer_video_demo/blob/main/uniformer.py).
I also give a demo in [app.py](https://huggingface.co/spaces/Sense-X/uniformer_video_demo/blob/main/app.py).

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
