### ISSUE TITLE
[Question for Video Classification] loading pretrained weights on the model and wrong test results issue 

### ISSUE THREAD

**Issue by DoranLyong** [Sense-X/UniFormer#54]
Thanks for your great work and I came back again with some questions :) 

I have already watched a few issues about loading and testing with the pre-trained weights: 
* [issue#22](https://github.com/Sense-X/UniFormer/issues/22)
* [issue#30](https://github.com/Sense-X/UniFormer/issues/30)

I think I followed the instructions and set options well, but I met wrong estimation results like below: 
![image](https://user-images.githubusercontent.com/13333380/171087509-f8e45647-392c-48ac-a9c5-e4a16f6cde35.png)

So, I want to show you how I did the process and hope to get some feedback ... 
*** 
### Step1. get and place the pretrained model 
![image](https://user-images.githubusercontent.com/13333380/171091197-3f54c753-d4dd-49de-b42c-f1838c7e85dc.png)
I achieved the [uniformer_small_k400_8x8.pth](https://github.com/Sense-X/UniFormer/tree/main/video_classification#kinetics-400) out of the link above.

Then, made `./path_to_models/` directory and placed it because ,in [slowfast/models/uniformer.py](https://github.com/Sense-X/UniFormer/blob/main/video_classification/slowfast/models/uniformer.py), the root directory for `model_path` is set like that.

https://github.com/Sense-X/UniFormer/blob/fdc1a646a3dac81a692877bcffa15e42db8e7df6/video_classification/slowfast/models/uniformer.py#L16-L26

### Step2. set configs 
I followed the test configs in [./exp/uniformer_s8x8_k400](https://github.com/Sense-X/UniFormer/tree/main/video_classification/exp/uniformer_s8x8_k400):
* [test.yaml](https://github.com/Sense-X/UniFormer/blob/main/video_classification/exp/uniformer_s8x8_k400/test.yaml) and [test.sh](https://github.com/Sense-X/UniFormer/blob/main/video_classification/exp/uniformer_s8x8_k400/test.sh)

I considered `test.yaml` as default and options in `test.sh` as dynamically changeable. Giving arguments by shell commands is good, but hard to debug for me, so I added extra code for setting `cfg` only. That is defined in `tools/run_net.py` like below: 

![image](https://user-images.githubusercontent.com/13333380/171094068-4d4f92b7-e12e-4bd6-816d-2157f38c093a.png)
![image](https://user-images.githubusercontent.com/13333380/171094090-1138d2b0-8f72-45e8-a5c3-bd14115e8916.png)

For now, I can change the config options like `test.sh`.

### Step3. run in debugging mode 
This section is for tracking if the defined model loading the pretrained `.pth` file well. 

(1) building the model is accessed by `from slowfast.models import build_model` like below:
https://github.com/Sense-X/UniFormer/blob/fdc1a646a3dac81a692877bcffa15e42db8e7df6/video_classification/tools/test_net.py#L161

(2) (by line 39-40) the `uniformer` architecture is loaded, and (by line42-46) the checkpoint from `.pth` file is loaded into the memory and try to assign to the model.
https://github.com/Sense-X/UniFormer/blob/e8024703bffb89cb7c7d09e0d774a0d2a9f96c25/video_classification/slowfast/models/build.py#L38-L46

(3) in `slowfast/utils/checkpoint.py`, this flow is for checking if the weights are loaded well to the corresponding layer. But, seeing below, many layers fail to load. I wonder if this is right or not. In intuition, It seems something is wrong. 
https://github.com/Sense-X/UniFormer/blob/e8024703bffb89cb7c7d09e0d774a0d2a9f96c25/video_classification/slowfast/utils/checkpoint.py#L333-L336

![image](https://user-images.githubusercontent.com/13333380/171097240-1cbde0e6-7195-4f5d-a3d0-bab0bec0a1df.png)

*** 
Those are how I tried for reproducing the results by the pretrained and what I met in error. I guess there is something wrong in <b>step3 - (3)</b>. 

Can you give me feedback on the above?

**Comment by Andy1621** [comment]
Sincerely sorry for the late response. Thanks for your detailed description!
I upload the wrong `test.yaml`, since the model is `UniFormer-S8x8`, the model depth should be `[3, 4, 8, 3]`. I have updated the `test.yaml` for `UniFormer-S8x8` by copying the `config.yaml` for training.

**Comment by DoranLyong** [comment]
Nice~ I give my thumb up ^^乃  
![image](https://user-images.githubusercontent.com/13333380/171981246-d37b6df3-2c73-4fd4-a4d9-f19d1adc1e59.png)

In addition, I want to say something for others to be noticed about the test process.
* If you get the Kinetics-400 dataset by [mmaction2](https://mmaction2.readthedocs.io/en/latest/supported_datasets.html#kinetics-400-600-700), [cvdfoundation's github](https://github.com/cvdfoundation/kinetics-dataset), or else, the test video list might be different with this repository; [test.csv](https://github.com/Sense-X/UniFormer/tree/main/video_classification/data_list/k400). 
* I get the `test.csv` in the latest version out of [deepmind.com](https://www.deepmind.com/open-source/kinetics).
* That's why my results with `Uniformer-S8x8` is less than [#issue22](https://github.com/Sense-X/UniFormer/issues/22); maybe? 

Unfortunately, there are still corrupted videos when downloading the latest K400 dataset. So, one needs to consider the above problem which I met.
* (P.S) Even though the list is different, I still followed the `name_to_index` rule like [here](https://github.com/Sense-X/UniFormer/blob/main/video_classification/data_list/k400/kinetics_400_categroies.txt)

**Comment by Andy1621** [comment]
Good response! Nice try! 
For Kinetics and Something-Something, researchers report the results in the **Validation dataset**, as in [issue42](https://github.com/Sense-X/UniFormer/issues/42#issuecomment-1113644150).
However, since there are some missed videos, there are different versions of Kinetics. Thus there are often some descriptions of the video number. Like in SlowFast, they use 20k validation dataset.
<img width="431" alt="image" src="https://user-images.githubusercontent.com/24236723/171995219-d6b6503f-2265-432f-905e-024b006f8c90.png">

Moreover, you can download the dataset I provided. Note that do not release the dataset public, since we do not achieve the permission.  The URL will not be available after 7 days.
URL: [https://pan.baidu.com/s/1XfW16nhONEDX-hvk4hl0CQ](https://pan.baidu.com/s/1XfW16nhONEDX-hvk4hl0CQ)
Password: vt03

```shell
cat xa* >> train_k400.zip
unzip train_k400.zip
```

**Comment by DoranLyong** [comment]
@Andy1621  Thanks to share your processed data... 

Unfortunately, I can't access to Baidu cloud without any account  as I'm a foreigner, and they stopped new registers living overseas to sign up :s.

Sorry to bother you, but can you share it in another way like using Google drive?

**Comment by Andy1621** [comment]
Sincerely sorry for the inconvenience. Since I don't have a backup on my personal computer, and I don't have enough space to upload the dataset, it is difficult to provide the dataset via Google drive.
For signing up, you may follow the step [here](https://www.adchina.io/how-to-open-a-baidu-account-outside-china/).

You can also download the dataset in [cvdfoundation's github](https://github.com/cvdfoundation/kinetics-dataset), which also contains more videos than those in [deepmind.com](https://www.deepmind.com/open-source/kinetics).

Besides, for the lower results, you may need to [resize the video to the short edge size of 320](https://github.com/Sense-X/UniFormer/blob/main/video_classification/DATASET.md) as in [issue45](https://github.com/Sense-X/UniFormer/issues/45).

**Comment by DoranLyong** [comment]
Thanks :)  I'm gonna try.
