### ISSUE TITLE
object detection('VOCDataset') 

### ISSUE THREAD

**Issue by 15129302710** [Sense-X/UniFormer#58]
whether the code of object detection is only useful with COCO dataset，what about VOCDataset. when I use 'VOCDataset' , the error is as follows:
<img width="785" alt="屏幕截图 2022-06-06 200135" src="https://user-images.githubusercontent.com/74938994/172157253-5516a1c9-b655-4978-8c35-43bab0b45112.png">
 please give me some advice ,thank you very much!

**Comment by Andy1621** [comment]
We just simply add the UniFormer model in MMDetection, thus it's impossible for the incompatibility of other datasets.

For the bug you meet, you'd better learn to localize the real reason. As shown in your report, it is mainly because of the bug in `apex`, you can fix the bug as [here](https://blog.csdn.net/starvapour/article/details/122275439).

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
