### ISSUE TITLE
Require Explanation inCode

### ISSUE THREAD

**Issue by AshwinRamachandran2002** [Sense-X/UniFormer#60]
https://github.com/Sense-X/UniFormer/blob/1ce70bcccbe72962813aedf5eb1209f318f859b6/video_classification/slowfast/models/uniformer.py#L454
Could you kindly shed light on what this line is doing ?

**Comment by Andy1621** [comment]
Thanks for your question!
Since our code is based on [SlowFast](https://github.com/facebookresearch/SlowFast), the dataloader will generate a list of data. For example, for SlowFast model, it will generate two input data for the slow way and fast way.

We simply adopt the first data as in [MViT](https://github.com/facebookresearch/SlowFast/blob/36c15af726b912e3c8fd0e5317642b31b1cd4339/slowfast/models/video_model_builder.py#L1027-L1028)

**Comment by AshwinRamachandran2002** [comment]
Oh ok. Thank you.
