### ISSUE TITLE
Local MHRA and PWConv-DWConv-PWConv

### ISSUE THREAD

**Issue by FrauSong** [Sense-X/UniFormer#7]
Hi,

Thanks for sharing this excellent paper and the code. Could you please give a detailed explanation of why the PWConv-DWConv-PWConv does the same thing as the Local MHRA? I understand that the 'spatiotemporal affinity' is content-dependent (similar to ViT), but the Conv layers in code are content-independent. Is the set of Conv layers the approximation of the Local MHRA? For the temporal dimension, how do you handle them before feeding the tensor to the network, concatenating all frames along the RGB channels (the Conv layers in the code are all 2d Conv)?

Thanks in advance!

Best regards

**Comment by Andy1621** [comment]
Sorry for late response.
Q1: Is the set of Conv layers the approximation of the Local MHRA? Why the PWConv-DWConv-PWConv does the same thing as the Local MHRA? 
A1: You can find the detailed description in Section 3.2.1. Via visualizations, we find that in the shallow layers of ViTs, self-attention focuses on capturing local features: (1) the activated tokens is in the local area (3x3); (2) the output features of the 3rd layer still maintain details. Though local self-attention is content-independent, it works more like convolution in the shallow layers, thus we try to utilize convolution rather than local self-attention. It is indeed content-independent but performs better to learn local details. As for why DWConv does the same thing as the Local MHRA, you can refer to papers like “[Demystifying Local Vision Transformer: Sparse Connectivity, Weight Sharing, and Dynamic Weight](https://arxiv.org/pdf/2106.04263.pdf)”
> Similarities. Depth-wise convolution resembles local attention in sparse connectivity. There are no connections across channels. Each position is only connected to the positions in a small local window for each channel.
Differences. One main difference lies in weight sharing: depth-wise convolution shares the connection weights across spatial positions, while local attention shares the weights across channels or within each group of channels.

Q2:  For the temporal dimension, how do you handle them before feeding the tensor to the network?
A2: Actually, we utilize 3D Conv in our video backbones. You can find the code in `video_classification/slowfast/models/uniformer.py`. Interestingly, as shown in Table 12 in [our paper](https://arxiv.org/abs/2201.09450), simply utilizing 2D conv is also not bad for sense-related datasets like Kinetics-400. In this way, we concatenate all frames along the RGB channels. We finally adopt 3D Conv due to the better performance and negligible computation.
 https://github.com/Sense-X/UniFormer/blob/48d7dbf7ba1f637bb8929265d3db3746b524aa47/video_classification/slowfast/models/uniformer.py#L117-L136

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.

**Comment by LostXine** [comment]
Hello,

Thanks for your great work. Just for clarification, according to this file you mentioned:

https://github.com/Sense-X/UniFormer/blob/e8024703bffb89cb7c7d09e0d774a0d2a9f96c25/video_classification/slowfast/models/uniformer.py#L117-L136

Does that mean you don't have multi-heads in this block, and all the channels are processed jointly?

Thank you.

**Comment by Andy1621** [comment]
@LostXine Actually, I use DWConv `conv_5x5x5(dim, dim, groups=dim)`.
And DWConv can be seen as a multi-head operation, wherein the `#head=#channel`. All the channels are processed individually. You can refer to more papers like [Demystifying Local Vision Transformer: Sparse Connectivity, Weight Sharing, and Dynamic Weight](https://arxiv.org/pdf/2106.04263.pdf) for the connection between DWConv and Self-Attention~~

**Comment by LostXine** [comment]
@Andy1621 I see. Thank you for your prompt reply 👍
