### ISSUE TITLE
Why the FPN 80k setting is different from PVT?

### ISSUE THREAD

**Issue by rayleizhu** [Sense-X/UniFormer#78]
I notice that you actually run (equivalent) 160k iterations for FPN 80k setting:
https://github.com/Sense-X/UniFormer/blob/1ce70bcccbe72962813aedf5eb1209f318f859b6/semantic_segmentation/fpn_seg/exp/fpn_global_small/config.py#L34

 This is different from original PVT's setting here :
https://github.com/whai362/PVT/blob/c64d4edf023f1657c6067f7e591a76315fa26892/segmentation/configs/sem_fpn/PVT/fpn_pvt_s_ade20k_40k.py#L25

Why do you change it? Is it fair comparison?

**Comment by Andy1621** [comment]
Since we use 2 nodes for a faster , there are actually 16 gpus, thus there are actually 80k steps.
We follow the scripts as `PVT`. That is why we use the parameter `gpu_multiples `.

Most of the papers do not show their training script for `FPN`, we are not sure how many gpu they used. Thus we simply ensure the total step is 80K as in (mmsegmentation)[https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/schedules/schedule_80k.py]

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
