### ISSUE TITLE
plt.get_cmap

### ISSUE THREAD

**Issue by W4ngH4o** [Sense-X/UniFormer#81]
When I utilize Grad_cam to visualize, the localization_map is not all 0. But after plt.get_cmap, the heatmap is all 0, which leads the visualization is black. I am confused and looking forward to your reply. Thanks so much.

![图片](https://user-images.githubusercontent.com/47959754/194810942-7c9079b2-bd75-4474-9900-2b32850da198.png)

**Comment by Andy1621** [comment]
I'm not sure what problem you met.
For visualization, I use this [repo](https://github.com/jacobgil/pytorch-grad-cam). 
Since it is designed for images, for videos, I use grad_cam in each frame, and interpolate the heatmap if the frames is downsampled.

For your question, since the visualization is forked from [PySlowfast](https://github.com/facebookresearch/SlowFast), I suggest you open an issue in their repo.

**Comment by W4ngH4o** [comment]
> I'm not sure what problem you met. For your question, since the visualization is forked from [PySlowfast](https://github.com/facebookresearch/SlowFast), I suggest you open an issue in their repo.
> 
> For my visualization, I use this [repo](https://github.com/jacobgil/pytorch-grad-cam). Since it is designed for images, for videos, I use grad_cam in each frame, and interpolate the heatmap if the frames are downsampled.

Thanks for your suggestion. I have resolved my problem.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
