### ISSUE TITLE
How to draw the figure 8?

### ISSUE THREAD

**Issue by hongsheng-Z** [Sense-X/UniFormer#89]
Hi, thanks for your great work. I want to use your [uniformer_base] to draw a graph like Fig.8. on my own image. How do I do this?

**Comment by hongsheng-Z** [comment]
Thanks for your reply. I have seen your updated _vis_ code. You have visualized it on K400 dataset, which is a dataset with categories. But now I'm using your model in my own data set, which doesn't have a category.txt file. What should I do? And the cam plot drawn is very discrete, which cannot reach the result I want.

**Comment by Andy1621** [comment]
Actually, you do not have to add `category`. I use it to compare the prediction and ground truth.

For the discrete cam, it's normal for Vision Transformer. Since the cam is designed for CNN, it is not very suitable for ViT sometimes.
For better visualization, you can use this [repo](https://github.com/hila-chefer/Transformer-Explainability).

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
